name: MinecraftPluginExp
version: 1.0
author: Michael Kooiker
main: mcpluginexp.Main
description: Experiment Minecraft Plugin
commands:
  test:
    description: A test command
    usage: /<command>
  test2:
    description: A test2 command
    usage: /<command>